### ISSUE TITLE
Can we make name more specific?

### ISSUE THREAD

**Issue by BohanHsu** [ahchoo/realtime#64]
Now, the game controller called game.js, the game models called game.js, the socket.io function module called game.js. Could we make it more specific? For example, game-controller.js, game-socket.js.
It's really confusing when open serval tab on editor with same name but different content.

**Comment by fuqcool** [comment]
The directory works like namespace. Say we have a model  **/lib/models/game.js**, the concept path will be **realtime.models.game**, instead of **realtime.models.gameModel**, which is verbose.

Yes, it's a little bit confusing in editors. Can you do a global path search to find those files? Like **models/game**

@BohanHsu
